/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 *
 * Generated by MATLAB(R) 7.1 and the Filter Design Toolbox 3.3.
 *
 * Generated on: 15-May-2011 17:16:05
 *
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II, Second-Order Sections
 * Number of Sections  : 4
 * Stable              : Yes
 * Linear Phase        : No
 * Arithmetic          : fixed
 * Numerator           : s16,14 -> [-2 2)
 * Denominator         : s16,14 -> [-2 2)
 * Scale Values        : s16,14 -> [-2 2)
 * Input               : s16,15 -> [-1 1)
 * Section Input       : s16,9 -> [-64 64)
 * Section Output      : s16,11 -> [-16 16)
 * Output              : s34,29 -> [-16 16)
 * State               : s16,15 -> [-1 1)
 * Numerator Prod      : s32,29 -> [-4 4)
 * Denominator Prod    : s32,29 -> [-4 4)
 * Numerator Accum     : s34,29 -> [-16 16)
 * Denominator Accum   : s34,29 -> [-16 16)
 * Round Mode          : convergent
 * Overflow Mode       : wrap
 */

/* General type conversion for MATLAB generated C-code  */
/* 
 * Expected path to tmwtypes.h 
 * D:\Matlab\extern\include\tmwtypes.h 
 */
#define MWSPT_NSEC 9
const int NL[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1 };
const int NUM[MWSPT_NSEC][3] = {
  {
    16311,      0,      0 
  },
  {
    16384, -32768,  16384 
  },
  {
    16181,      0,      0 
  },
  {
    16384, -32768,  16384 
  },
  {
    16083,      0,      0 
  },
  {
    16384, -32768,  16384 
  },
  {
    16031,      0,      0 
  },
  {
    16384, -32768,  16384 
  },
  {
    16384,      0,      0 
  }
};
const int DL[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1 };
const int DEN[MWSPT_NSEC][3] = {
  {
    16384,      0,      0 
  },
  {
    16384, -32618,  16242 
  },
  {
    16384,      0,      0 
  },
  {
    16384, -32358,  15982 
  },
  {
    16384,      0,      0 
  },
  {
    16384, -32162,  15786 
  },
  {
    16384,      0,      0 
  },
  {
    16384, -32057,  15681 
  },
  {
    16384,      0,      0 
  }
};
