/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 *
 * Generated by MATLAB(R) 7.1 and the Filter Design Toolbox 3.3.
 *
 * Generated on: 15-May-2011 17:16:44
 *
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II
 * Numerator Length    : 3
 * Denominator Length  : 3
 * Stable              : Yes
 * Linear Phase        : No
 * Arithmetic          : fixed
 * Numerator           : s16,14 -> [-2 2)
 * Denominator         : s16,14 -> [-2 2)
 * Input               : s16,15 -> [-1 1)
 * Output              : s34,29 -> [-16 16)
 * State               : s16,15 -> [-1 1)
 * Numerator Prod      : s32,29 -> [-4 4)
 * Denominator Prod    : s32,29 -> [-4 4)
 * Numerator Accum     : s34,29 -> [-16 16)
 * Denominator Accum   : s34,29 -> [-16 16)
 * Round Mode          : convergent
 * Overflow Mode       : wrap
 */

/* General type conversion for MATLAB generated C-code  */
/* 
 * Expected path to tmwtypes.h 
 * D:\Matlab\extern\include\tmwtypes.h 
 */
const int NL2 = 3;
const int NUM2[3] = {
    16380, -32695,  16380
};
const int DL2 = 3;
const int DEN2[3] = {
    16384, -32695,  16376
};
