#ifndef _Filtry
#define _Filtry

extern float x_notch[3],y_notch[3];
extern float x_pass[9][3], y_pass[9][3];

///
/// Funkcja inicjalizujaca filtry
///
void Filtr_init();

/*!
 * Funkcja obslugujaca dzialanie filtru blokujacego 50Hz
 *
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 *
 * Generated by MATLAB(R) 7.1 and the Filter Design Toolbox 3.3.
 *
 * Generated on: 15-May-2011 17:16:44
 *
 * Discrete-Time IIR Filter (real)
 *
 * -------------------------------
 *
 * Filter Structure    : Direct-Form II
 *
 * Numerator Length    : 3
 *
 * Denominator Length  : 3
 *
 * Stable              : Yes
 *
 * Linear Phase        : No
 *
 * Arithmetic          : fixed
 *
 * Numerator           : s16,14 -> [-2 2)
 *
 * Denominator         : s16,14 -> [-2 2)
 *
 * Input               : s16,15 -> [-1 1)
 *
 * Output              : s34,29 -> [-16 16)
 *
 * State               : s16,15 -> [-1 1)
 *
 * Numerator Prod      : s32,29 -> [-4 4)
 *
 * Denominator Prod    : s32,29 -> [-4 4)
 *
 * Numerator Accum     : s34,29 -> [-16 16)
 *
 * Denominator Accum   : s34,29 -> [-16 16)
 *
 * Round Mode          : convergent
 *
 * Overflow Mode       : wrap
 */
inline float Notching(float value);

/*!
  Funkcja obslugujaca dzialanie filtru gornoprzepustowego

  Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool

  Generated by MATLAB(R) 7.1 and the Filter Design Toolbox 3.3.

  Generated on: 15-May-2011 17:16:05

  Discrete-Time IIR Filter (real)

  -------------------------------

  Filter Structure    : Direct-Form II, Second-Order Sections

  Number of Sections  : 4

  Stable              : Yes

  Linear Phase        : No

  Arithmetic          : fixed

  Numerator           : s16,14 -> [-2 2)

  Denominator         : s16,14 -> [-2 2)

  Scale Values        : s16,14 -> [-2 2)

  Input               : s16,15 -> [-1 1)

  Section Input       : s16,9 -> [-64 64)

  Section Output      : s16,11 -> [-16 16)

  Output              : s34,29 -> [-16 16)

  State               : s16,15 -> [-1 1)

  Numerator Prod      : s32,29 -> [-4 4)

  Denominator Prod    : s32,29 -> [-4 4)

  Numerator Accum     : s34,29 -> [-16 16)

  Denominator Accum   : s34,29 -> [-16 16)

  Round Mode          : convergent

  Overflow Mode       : wrap
 */
inline float HighPass(float value);

#endif
